FROM cgr.dev/chainguard/wolfi-base:latest

RUN apk add --no-cache python-3.12 py3.12-pip

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

EXPOSE 8080
CMD ["python", "app.py"]
